export CUDA_ROOT="/data/liuzhuang/cuda"
export CUDA_INC_DIR="/data/liuzhuang/cuda/include"
export PATH="$PATH:/data/liuzhuang/cuda/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/liuzhuang/cuda/lib64"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/liuzhuang/tensorrt/lib"